### ISSUE TITLE
issue with finding modules

### ISSUE THREAD

**Issue by Hololensmoon** [Annusha/lirec#1]
I have done all the steps up until step 3 but when I run "python resume/modalities.py", I got an error indicating "No module named 'mixed_utils'. Could you please help me what can be the problem?

**Comment by Hololensmoon** [comment]
I actually solved the issue by uncommenting a line in "modalities.py". The other problem I have is that "plotly" is not in the requirements.txt but you have used it in "classification_dataloader.py". I tried to install it but I'm encountering package incompatibility which denies me from installing plotly.

**Comment by Annusha** [comment]
Thanks for your interest in the work! 
Do you still encounter problems?
