### ISSUE TITLE
hi,dataset query ! (●'◡'●)

### ISSUE THREAD

**Issue by jun0wanan** [Annusha/lirec#2]
hi , beautiful  author ~:

   Your work is  perfect and interesting . How can we get the bbox of a whole person (raw dataset is only give person of face) ? 

Hope to get your reply ~ 

Best wishes

jun0

**Comment by Annusha** [comment]
Hi!
Thanks a lot! :)

You can approximate body from the face. Of course it's not perfect.
For the reference how I did that check the function get_features_by_track()  in the file /visual_utils/visual_features.py
Hope it will help

Best,
Anna

**Comment by jun0wanan** [comment]
hi, thank you your reply o(*￣▽￣*)ブ

Can you share us your raw video ~~? I want to make some proceed. However , I find some video I download that have time different from the timestamp in raw dataset

hope to get your reply (●'◡'●) 

best.
jun0
