### ISSUE TITLE
hi,dear author about dataset

### ISSUE THREAD

**Issue by jun0wanan** [Annusha/lirec#3]
Dear author，
         I'm sorry to bother you again. When I used the original data set to extract more information features, I found that the faces of some videos could not match the faces of the videos themselves. How did you deal with them? 
         Hope you can reply me .. I want to graduate /(ㄒoㄒ)/~~

Best wishes，
jun0

**Comment by Annusha** [comment]
Hi!
No problem, I wanted to answer the previous issue, but you've already closed it.. 

Could you please be more detailed about what is not matching?
You can also contact me via email

Best,
Anna

**Comment by jun0wanan** [comment]
> Hi!
> No problem, I wanted to answer the previous issue, but you've already closed it..
> 
> Could you please be more detailed about what is not matching?
> You can also contact me via email
> 
> Best,
> Anna

I have send you a email  (●'◡'●)

**Comment by jun0wanan** [comment]
> Hi!
> No problem, I wanted to answer the previous issue, but you've already closed it..
> 
> Could you please be more detailed about what is not matching?
> You can also contact me via email
> 
> Best,
> Anna

Hi,
   Anna,the feature(52G)  download very slowly (and can't be continued if the download is suspended), I wonder if you have other channels to share?


Best,
jun

**Comment by Annusha** [comment]
Hi,

let me check, probably I can chunk the data into smaller parts.

Best,
Anna

**Comment by Annusha** [comment]
try to use wget -c option to continue download if it's interrupted.

**Comment by jun0wanan** [comment]
HTTP request sent, awaiting response... 200 OK
Length: 56320987738 (52G) [application/x-gzip]
Saving to: ‘features.tar.gz’

features.tar.gz       45%[========>           ]  24.02G  1.40KB/s    in 10h 7m  

2021-02-23 20:37:47 (691 KB/s) - Read error at byte 25792839680/56320987738 (Success). Retrying.

--2021-02-23 20:37:48--  (try: 2)  https://www.rocq.inria.fr/cluster-willow/mtapaswi/downloads/anna_cvpr2020/features.tar.gz
Connecting to www.rocq.inria.fr (www.rocq.inria.fr)|128.93.96.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56320987738 (52G) [application/x-gzip]
Saving to: ‘features.tar.gz’

features.tar.gz       10%[=>                  ]   5.52G   105KB/s    eta 16h 24m^C

**Comment by jun0wanan** [comment]
> try to use wget -c option to continue download if it's interrupted.

hi,anna:

 In paper:  We extract visual features for all clips using a ResNeXt-101 model [20] pre-trained on the Kinetics-400
dataset. A batch of 16 consecutive frames is encoded, and feature maps are global average-pooled for the clip representation, and average pooled over a region of interest (ROIPool) to represent characters . .  How can I do that ~~
        Hope to get your reply!

best,
jun

**Comment by Annusha** [comment]
Hi Jun,

you can use models from there:
https://modelzoo.co/model/3d-resnets-pytorch

Bounding boxes for all characters are available in the moviegraph annotations.
Hope it helps! 

Best,
Anna

Best,
Anna

**Comment by jun0wanan** [comment]
> Hi Jun,
> 
> you can use models from there:
> https://modelzoo.co/model/3d-resnets-pytorch
> 
> Bounding boxes for all characters are available in the moviegraph annotations.
> Hope it helps!
> 
> Best,
> Anna
> 
> Best,
> Anna

hi,

you  use the frame the bbox belong to ? how do you do that ~ Maybe  if  frame = 0 , bbox=(...) you will choose 0th segment or if frame=17,bbox=(..) you will choose 1th segment ? Is that true ?

Best,
